"""
Core utilities for memory_bacon system
"""
from .config import (
    DEFAULT_API_KEY_PATH,
    EMBEDDING_MODEL,
    DEFAULT_K_NEIGHBORS,
    DEFAULT_RETRIEVAL_K,
    DEFAULT_MEMORY_FILE,
    SCHEMA_VERSION,
    VERBOSE_TIMING
)

__all__ = [
    'DEFAULT_API_KEY_PATH',
    'EMBEDDING_MODEL',
    'DEFAULT_K_NEIGHBORS',
    'DEFAULT_RETRIEVAL_K',
    'DEFAULT_MEMORY_FILE',
    'SCHEMA_VERSION',
    'VERBOSE_TIMING'
]
